---
    - name: Update system packages
      apt:
        upgrade: True
        update_cache: True
        state: latest

    - name: Create ghostblog group
      group:
        name: "{{ ghost_user }}"
        state: present

    - name: Create ghostblog user
      user:
        name: "{{ ghost_user }}"
        shell: /bin/bash
        group: "{{ ghost_user }}"
        update_password: on_create
        password: "{{ ghost_user_pwd }}"

    - name: Add ghostblog user to sudo group
      shell: usermod -aG sudo "{{ ghost_user }}"

    - name: Create ~/.ssh dir
      file:
        path: /home/{{ ghost_user }}/.ssh
        state: directory
        owner: "{{ ghost_user }}"
        group: "{{ ghost_user }}"
        mode: '0700'

    - name: Copy my ssh keys
      copy:
        src: /home/belluu/.ssh/id_rsa.pub
        dest: /home/{{ ghost_user }}/.ssh/authorized_keys
        owner: "{{ ghost_user }}"
        group: "{{ ghost_user }}"
        mode: '0600'

    - name: Ensure NodeJS 12 repository is present
      shell: curl -sL https://deb.nodesource.com/setup_12.x | sudo -E bash

    - name: Ensure required packages are installed
      apt:
        name:
          - nginx
          - nodejs
          - python3
          - python3-pip
          - python3-pexpect
          - mysql-client
          - mysql-common
          - mysql-server

    - name: Ensure default python interpreter is in 3.x version
      lineinfile:
        path: /root/.bashrc
        line: alias python='/usr/bin/python3.8'
        create: True

    - name: Set password for root user in mysql
      command: mysql -u root --execute="ALTER USER 'root'@'localhost' IDENTIFIED WITH mysql_native_password BY 'password'"

    - name: Flush privileges in MySQL
      command: mysql --user=root --password=password --execute="flush privileges;"